"""new update

Revision ID: 5a48ccc27493
Revises: 7336f80d8bf6
Create Date: 2025-08-28 16:49:30.748343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a48ccc27493'
down_revision: Union[str, None] = '7336f80d8bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_history_user_UUID', table_name='chat_history')
    op.drop_column('chat_history', 'user_UUID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('user_UUID', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_chat_history_user_UUID', 'chat_history', ['user_UUID'], unique=False)
    # ### end Alembic commands ###
