"""new update

Revision ID: 7336f80d8bf6
Revises: cc7f67fa97c4
Create Date: 2025-08-28 12:54:49.694200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7336f80d8bf6'
down_revision: Union[str, None] = 'cc7f67fa97c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jero_test')
    op.add_column('articles', sa.Column('article_id', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('title', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('content', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('link', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('author', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('categories', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('tags', sa.String(), nullable=True))
    op.drop_index('ix_articles_auteur', table_name='articles')
    op.drop_index('ix_articles_contenu', table_name='articles')
    op.drop_index('ix_articles_date', table_name='articles')
    op.drop_index('ix_articles_titre', table_name='articles')
    op.create_index(op.f('ix_articles_article_id'), 'articles', ['article_id'], unique=True)
    op.create_index(op.f('ix_articles_author'), 'articles', ['author'], unique=False)
    op.create_index(op.f('ix_articles_content'), 'articles', ['content'], unique=False)
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=False)
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=False)
    op.drop_column('articles', 'titre')
    op.drop_column('articles', 'contenu')
    op.drop_column('articles', 'auteur')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('auteur', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('contenu', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('titre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_index(op.f('ix_articles_content'), table_name='articles')
    op.drop_index(op.f('ix_articles_author'), table_name='articles')
    op.drop_index(op.f('ix_articles_article_id'), table_name='articles')
    op.create_index('ix_articles_titre', 'articles', ['titre'], unique=False)
    op.create_index('ix_articles_date', 'articles', ['date'], unique=False)
    op.create_index('ix_articles_contenu', 'articles', ['contenu'], unique=False)
    op.create_index('ix_articles_auteur', 'articles', ['auteur'], unique=False)
    op.drop_column('articles', 'tags')
    op.drop_column('articles', 'categories')
    op.drop_column('articles', 'author')
    op.drop_column('articles', 'slug')
    op.drop_column('articles', 'link')
    op.drop_column('articles', 'content')
    op.drop_column('articles', 'title')
    op.drop_column('articles', 'article_id')
    op.create_table('jero_test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('questions', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('responses', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='jero_test_pkey')
    )
    # ### end Alembic commands ###
